# Generated by Django 4.1.5 on 2023-01-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.AddField(
            model_name='direction',
            name='key',
            field=models.CharField(max_length=255, null=True, verbose_name='Ключ направления'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
