# Generated by Django 4.1.5 on 2023-01-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_userprofile_is_active_userprofile_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='title',
        ),
        migrations.AddField(
            model_name='direction',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Название направления'),
        ),
    ]
